name: Deploy React Application

on:
  push:
    branches:
      - main

jobs:
  build_test:
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v2
      
      - name: npm ci and build
        working-directory: ./frontend
        run: |
          npm ci
          npm run build --if-present
        
      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./frontend/build          
